---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - ebdnquay.ebdnlab.vmware.tamlab.rdu2.redhat.com:8443/mod-certifiedv414/nutanix
    source: registry.connect.redhat.com/nutanix
  - mirrors:
    - ebdnquay.ebdnlab.vmware.tamlab.rdu2.redhat.com:8443/mod-certifiedv414/sig-storage
    source: registry.k8s.io/sig-storage
  - mirrors:
    - ebdnquay.ebdnlab.vmware.tamlab.rdu2.redhat.com:8443/mod-certifiedv414/openshift4
    source: registry.redhat.io/openshift4
