apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-my-certified-catalog
  namespace: openshift-marketplace
spec:
  image: ebdnquay.ebdnlab.vmware.tamlab.rdu2.redhat.com:8443/mod-certifiedv414/my-certified-catalog:v4.14
  sourceType: grpc
